version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./.Dockerfile
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    command: npm run dev

  postgres-db:
    container_name: postgres-db
    env_file: ./.env.postgres
    image: postgres:alpine
    restart: always
    env_file:
      - ./.env.postgres
    ports:
      - "5432:5432"