version: "3.2"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./.Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres-db
    ports:
      - "4000:4000"

  postgres-db:
    volumes:
      - ./db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-db