version: "3"
services:
  postgres-db:
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bread
    image: postgres:alpine
    restart: always
    volumes:
      - ./db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./.Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres-db
    ports:
      - "4000:4000"
