version: "3.7"
services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    volumes:
      - ./db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-connect

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./.Dockerfile-test
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres-db
    ports:
      - "4000:4000"
    networks:
      - app-connect


networks:
    app-connect:
        driver: bridge